# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('failed_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=b'2019-11-14'),
        ),
    ]
