# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-13 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='Task',
        ),
    ]
